//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCCP.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomMessage
    {
        public int ChatRoomMessageId { get; set; }
        public int ChatRoomId { get; set; }
        public int SenderUserId { get; set; }
        public string SenderDisplayName { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
        public string Message { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    }
}
