//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCCP.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralEnquiryIncidentLink
    {
        public int GeneralEnquiryIncidentLinkId { get; set; }
        public int GeneralEnquiryId { get; set; }
        public int IncidentTypeId { get; set; }
        public int IncidentId { get; set; }
    }
}
