//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCCP.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentType
    {
        public int IncidentTypeId { get; set; }
        public string IncidentType1 { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
    }
}
