//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCCP.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputOption
    {
        public int InputOptionId { get; set; }
        public string InputKey { get; set; }
        public string Value { get; set; }
        public Nullable<short> SortingOrder { get; set; }
        public Nullable<bool> HasLogic { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
