//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCCP.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMSEvent
    {
        public int OMSEventId { get; set; }
        public string OMSNo { get; set; }
        public string AffectedArea { get; set; }
        public string AffectedArea_Chi { get; set; }
        public string AffectedBuilding { get; set; }
        public string AffectedBuilding_Chi { get; set; }
        public string AffectedStreet { get; set; }
        public string AffectedStreet_Chi { get; set; }
        public Nullable<System.DateTime> OutageStartTime { get; set; }
        public Nullable<System.DateTime> FullRestoration { get; set; }
        public Nullable<short> NoOfBuilding { get; set; }
        public Nullable<int> NoOfCustomerAffected { get; set; }
        public Nullable<int> NoOfPlatinumCustomer { get; set; }
        public Nullable<int> NoOfDiamondCustomer { get; set; }
        public Nullable<int> NoOfGoldCustomer { get; set; }
        public Nullable<int> NoOfSilverCustomer { get; set; }
        public string PossibleCause { get; set; }
        public string PossibleCause_Chi { get; set; }
        public Nullable<System.DateTime> ExpectedRestorationDateTime { get; set; }
        public Nullable<short> ExpectedRestorationTime { get; set; }
        public string RestorationMethod { get; set; }
        public string RestorationMethod_Chi { get; set; }
        public string StatusUpdateCode { get; set; }
        public string StatusUpdate { get; set; }
        public string RootCause { get; set; }
        public string RootCause_Chi { get; set; }
        public Nullable<bool> MVOutage { get; set; }
        public Nullable<bool> LVOutage { get; set; }
        public string Points { get; set; }
        public Nullable<bool> CriticalPoint { get; set; }
        public Nullable<bool> Reviewed { get; set; }
        public string OMSStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    }
}
