//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Func_Back {
            get {
                return ResourceManager.GetString("Func_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Func_Cancel {
            get {
                return ResourceManager.GetString("Func_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Enquiry.
        /// </summary>
        internal static string Func_CloseEnquiry {
            get {
                return ResourceManager.GetString("Func_CloseEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Incident.
        /// </summary>
        internal static string Func_CloseIncident {
            get {
                return ResourceManager.GetString("Func_CloseIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Func_Create {
            get {
                return ResourceManager.GetString("Func_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Incident.
        /// </summary>
        internal static string Func_CreateIncident {
            get {
                return ResourceManager.GetString("Func_CreateIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Func_Delete {
            get {
                return ResourceManager.GetString("Func_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Func_Details {
            get {
                return ResourceManager.GetString("Func_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Func_Edit {
            get {
                return ResourceManager.GetString("Func_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalate to Crisis.
        /// </summary>
        internal static string Func_EscalateToCrisis {
            get {
                return ResourceManager.GetString("Func_EscalateToCrisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Func_Export {
            get {
                return ResourceManager.GetString("Func_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link General Enquiry.
        /// </summary>
        internal static string Func_LinkGeneralEnquiry {
            get {
                return ResourceManager.GetString("Func_LinkGeneralEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Incident.
        /// </summary>
        internal static string Func_LinkIncident {
            get {
                return ResourceManager.GetString("Func_LinkIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Reviewed.
        /// </summary>
        internal static string Func_MarkReviewed {
            get {
                return ResourceManager.GetString("Func_MarkReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Func_Save {
            get {
                return ResourceManager.GetString("Func_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Func_Update {
            get {
                return ResourceManager.GetString("Func_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel this incident?.
        /// </summary>
        internal static string Label_Cancelncident {
            get {
                return ResourceManager.GetString("Label_Cancelncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to close this Enquiry?.
        /// </summary>
        internal static string Label_CloseEnquiry {
            get {
                return ResourceManager.GetString("Label_CloseEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to close this Incident?.
        /// </summary>
        internal static string Label_CloseIncident {
            get {
                return ResourceManager.GetString("Label_CloseIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to create a new Incident?.
        /// </summary>
        internal static string Label_CreateIncident {
            get {
                return ResourceManager.GetString("Label_CreateIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this incident?.
        /// </summary>
        internal static string Label_DeleteIncident {
            get {
                return ResourceManager.GetString("Label_DeleteIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Label_History {
            get {
                return ResourceManager.GetString("Label_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to mark this OMS Event reviewed?.
        /// </summary>
        internal static string Label_MarkReviewed {
            get {
                return ResourceManager.GetString("Label_MarkReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail Export.
        /// </summary>
        internal static string Menu_AuditTrailExport {
            get {
                return ResourceManager.GetString("Menu_AuditTrailExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Data Maintenance.
        /// </summary>
        internal static string Menu_BusinessDataMaintenance {
            get {
                return ResourceManager.GetString("Menu_BusinessDataMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Maintenance.
        /// </summary>
        internal static string Menu_ChecklistMaintenance {
            get {
                return ResourceManager.GetString("Menu_ChecklistMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crisis Approval.
        /// </summary>
        internal static string Menu_CrisisApproval {
            get {
                return ResourceManager.GetString("Menu_CrisisApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crisis Management.
        /// </summary>
        internal static string Menu_CrisisManagement {
            get {
                return ResourceManager.GetString("Menu_CrisisManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Enquiry.
        /// </summary>
        internal static string Menu_GeneralEnquiry {
            get {
                return ResourceManager.GetString("Menu_GeneralEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment - Air Emission.
        /// </summary>
        internal static string Menu_IncidentEnvironmentAirEmission {
            get {
                return ResourceManager.GetString("Menu_IncidentEnvironmentAirEmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment - Leakage.
        /// </summary>
        internal static string Menu_IncidentEnvironmentLeakage {
            get {
                return ResourceManager.GetString("Menu_IncidentEnvironmentLeakage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Management.
        /// </summary>
        internal static string Menu_IncidentManagement {
            get {
                return ResourceManager.GetString("Menu_IncidentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OHS.
        /// </summary>
        internal static string Menu_IncidentOHS {
            get {
                return ResourceManager.GetString("Menu_IncidentOHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality - Corporate Image.
        /// </summary>
        internal static string Menu_IncidentQualityCorporateImage {
            get {
                return ResourceManager.GetString("Menu_IncidentQualityCorporateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality - Generation.
        /// </summary>
        internal static string Menu_IncidentQualityGeneration {
            get {
                return ResourceManager.GetString("Menu_IncidentQualityGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality - Network.
        /// </summary>
        internal static string Menu_IncidentQualityNetwork {
            get {
                return ResourceManager.GetString("Menu_IncidentQualityNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System - Billing.
        /// </summary>
        internal static string Menu_IncidentSystemBilling {
            get {
                return ResourceManager.GetString("Menu_IncidentSystemBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System - Call Centre.
        /// </summary>
        internal static string Menu_IncidentSystemCallCentre {
            get {
                return ResourceManager.GetString("Menu_IncidentSystemCallCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System - Invoicing.
        /// </summary>
        internal static string Menu_IncidentSystemInvoicing {
            get {
                return ResourceManager.GetString("Menu_IncidentSystemInvoicing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System - IT System.
        /// </summary>
        internal static string Menu_IncidentSystemITSystem {
            get {
                return ResourceManager.GetString("Menu_IncidentSystemITSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System - Network Connectivity.
        /// </summary>
        internal static string Menu_IncidentSystemNetworkConnectivity {
            get {
                return ResourceManager.GetString("Menu_IncidentSystemNetworkConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System - OT System.
        /// </summary>
        internal static string Menu_IncidentSystemOTSystem {
            get {
                return ResourceManager.GetString("Menu_IncidentSystemOTSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System - Security.
        /// </summary>
        internal static string Menu_IncidentSystemSecurity {
            get {
                return ResourceManager.GetString("Menu_IncidentSystemSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMS Event Management.
        /// </summary>
        internal static string Menu_OMSEventManagement {
            get {
                return ResourceManager.GetString("Menu_OMSEventManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Menu_Report {
            get {
                return ResourceManager.GetString("Menu_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Details.
        /// </summary>
        internal static string Menu_ReportIncidentDetails {
            get {
                return ResourceManager.GetString("Menu_ReportIncidentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Details for COT.
        /// </summary>
        internal static string Menu_ReportIncidentDetailsForCOT {
            get {
                return ResourceManager.GetString("Menu_ReportIncidentDetailsForCOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Summary.
        /// </summary>
        internal static string Menu_ReportIncidentSummary {
            get {
                return ResourceManager.GetString("Menu_ReportIncidentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Maintenance.
        /// </summary>
        internal static string Menu_RoleMaintenance {
            get {
                return ResourceManager.GetString("Menu_RoleMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Maintenance.
        /// </summary>
        internal static string Menu_UserAccountMaintenance {
            get {
                return ResourceManager.GetString("Menu_UserAccountMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string Sidebar_GeneralSettings {
            get {
                return ResourceManager.GetString("Sidebar_GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Sidebar_Language {
            get {
                return ResourceManager.GetString("Sidebar_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCCP.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string UserMenu_Profile {
            get {
                return ResourceManager.GetString("UserMenu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string UserMenu_Signout {
            get {
                return ResourceManager.GetString("UserMenu_Signout", resourceCulture);
            }
        }
    }
}
