//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCCP.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistAction
    {
        public int ChecklistActionId { get; set; }
        public int ChecklistId { get; set; }
        public string Action { get; set; }
        public string ActionStatus { get; set; }
        public Nullable<bool> IsCompulsory { get; set; }
        public Nullable<short> AlertThreshold { get; set; }
        public Nullable<short> SortingOrder { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
    }
}
